### PR TITLE
test: use the new testkit library

### PR DESCRIPTION
**Pull request by mirko-felice**

### CODE REVIEW

**Comment by mirko-felice** [comment]
The failure is related to the fact that the tests run in the same temporary directory.
It is designed is this way to allow the users to test different outcomes, like running twice the same task should be UP-TO-DATE.

Otherwise, like you did before, you run the test every time in another directory.
In this case that works, but does not allow customizable tests.

**Comment by DanySK** [comment]
Nope, there should be an option to decide whether or not to start fresh, defaulting to true

**Comment by mirko-felice** [comment]
Do you mean an option for all tests?

Otherwise it can be possible that only some tests should be fresh.
It would complicate the design but I can try to do in this way too.

**Comment by mirko-felice** [comment]
In the second case, the design is not much more complicated but it can be a bit ambiguous to the user, because it has to set the property in all the tests that want to run in the same directory.
Should we take this design?
Example below:
image

**Comment by DanySK** [comment]
what about:

```yaml
tests:
  - description: ...
    target-folder: 'pluto'
    ...
  - description: ...
    target-folder: 'pluto'
```

or, even better, dependencies across tests. That would be valuable!

```yaml
tests:
  - id: myTest
    description: ...
    ...
  - description: ...
    requires:
      - myTest
```

basically, the second test must run after the former, and inside the same folder. Doable?

**Comment by mirko-felice** [comment]
Even dependencies are doable, but there are two issues:
1. Each test must have an ID, even if not required by the user (maybe can be generated randomly).
2. Like in the example below, where there are 2 independent tests and one requires both, which would be the folder? 
Test1 and Test2 should be independent but Test3 which requires both of them can't be run in both folders at the same time.

```yaml
tests:
  - id: test1
    description: ...
    ...
  - id: test2
    description: ...
    ...
  - id: test3
    description: ...
    requires:
      - test1
      - test2
  - id: test4
    description: ...
    requires:
      - test3
```

**Comment by DanySK** [comment]
1. Nope, it can be optional
2. Good call. The example should fail with a clear error, but if  we need all those tests to be in the same folder, we may just have a single dependency instead of a list.

**Comment by mirko-felice** [comment]
Ok, so we should accept only 1 requires and not a list? Like this:
```yaml
tests:
  - id: test1
    description: ...
    ...
  - id: test2
    description: ...
    requires: test1
  - id: test3
    description: ...
    requires: test2
  - id: test4
    description: ...
    requires: test3
```

**Comment by DanySK** [comment]
Yeah, looks fine

**Pull request merged**
